version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - coverage run -m pytest tests/test_app.py -v --junitxml=unit_tests_report.xml
      - coverage run -a -m pytest tests/test_integration.py -v --junitxml=integration_tests_report.xml
      - coverage report -m
      - coverage xml -i -o coverage.xml
      - pylint app.py --output-format=parseable > pylint_report.txt
artifacts:
  files:
    - '**/*'
    - coverage.xml
