version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - coverage run -m pytest tests/test_app.py -v --junitxml=unit_tests_report.xml
      - coverage run -a -m pytest tests/test_integration.py -v --junitxml=integration_tests_report.xml
      - coverage report -m
      - coverage xml -i -o coverage.xml

reports:
  unit-test-report:
    files:
      - 'unit_tests_report.xml'
    file-format: 'JUNITXML'
  integration-test-report:
    files:
      - 'integration_tests_report.xml'
    file-format: 'JUNITXML'
  coverage-report:
    files:
      - 'coverage.xml'
    file-format: 'COBERTURAXML'

artifacts:
  files:
    - '**/*'
